My portifolio
DebbyBud/Portifolio-setup pull request #2
Opened 2022-08-20 15:53 UTC by DebbyBud

The mobile version of my portifolio

2022-08-20 17:01 UTC, vickymarz requested changes
Hi @DebbyBud, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] I think it would be better if your PR title and description are professional and descriptive 😄 . Your PR title should describe the feature you working on in action word
e.g
Instead of writing _**My portfolio**_ as the PR title, you can write _**Portfolio setup and mobile first**_ which is the feature you worked on 👍🏼  

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- I would strongly recommend you commit your work bit by bit instead of making a single commit after all the activity is completed. In case there are errors that are difficult to handle, you can revert back to your previous commits thereby saving you useful time 😄 

- I think it would be better if you save your images in a folder so that your project will be well organized and easier to maintain 👍🏼. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 17:01 UTC, vickymarz commented on index.html
> +                        <li class="F5">Ruby on Rails</li>
- [ ] KIndly remove the bullet points you added in your design and align them properly to match the Figma design template chosen 👍🏼. kindly use the appropriate `font-size` as well to make your design nice and neat. 

You can use flexbox to align the technologies as shown in the design. You can watch this [video](https://www.youtube.com/watch?v=JJSoEo8JSnc) on how to use flexbox

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/185758248-45d9d183-89ce-4d7a-ad22-5c5555dc5f7d.png)  | ![image](https://user-images.githubusercontent.com/63473584/185758271-acb61762-b357-4804-a336-0a639859fd47.png)  |

2022-08-22 11:12 UTC, prolajumokeoni requested changes
Hi @DebbyBud, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 11:12 UTC, prolajumokeoni commented on index.html
> +            </ul>
- [ ] Kindly move all these elements into the headline section above, all these should be part of the headline section 👍🏿

2022-08-22 11:12 UTC, prolajumokeoni commented on index.html
> +            </ul>
- [ ] Please make sure that the links to your images are properly added this is currently missing in your design 👍🏿 
- [ ]  Kindly add alt texts to all images, please do this because if your image is not rendered due to network issues or a broken link, users can still see a text that says what the image about, this make your website more accessible

2022-08-22 11:12 UTC, prolajumokeoni commented on index.html
> +    <section class="header">
Figma Design          |  Your design    
:-------------------------:|:-------------------------:
![Screenshot_402](https://user-images.githubusercontent.com/69638013/185906762-0906ad5b-c379-48e4-b65a-6c59271d2865.png) |  ![Screenshot_403](https://user-images.githubusercontent.com/69638013/185907149-2cab45cd-3285-49ec-b2ba-a37eec74e791.png)

- [ ] Kindly add the right background image using img in CSS to your design this is currently missing
- Please note that your background image should be added to the headline section 👍🏿

2022-08-22 11:21 UTC, DebbyBud commented on index.html
> +        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
the last review told me to move into the header section

2022-08-22 13:08 UTC, mwanawabangona requested changes
Hi, @,

Great work on making the changes requested by a previous reviewer 👏
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 13:08 UTC, mwanawabangona commented on index.html
> +
- [ ] Kindly implement this change which was requested by the previous reviewer

 Figma Design
 ![Screenshot_402](https://user-images.githubusercontent.com/69638013/185906762-0906ad5b-c379-48e4-b65a-6c59271d2865.png)	
	Your design
![Screenshot_403](https://user-images.githubusercontent.com/69638013/185907149-2cab45cd-3285-49ec-b2ba-a37eec74e791.png)
 * [ ]  Kindly add the right background image using img in CSS to your design this is currently missing
 * Please note that your background image should be added to the headline section 👍🏿

2022-08-22 14:49 UTC, ShahierNashaat requested changes
Hi @DebbyBud, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 14:49 UTC, ShahierNashaat commented on style.css
> +  }
- [ ] Kindly use another unit instead of `vh` as it is making your page not responsive.

2022-08-22 15:40 UTC, KDlamini approved these changes
### Hi @DebbyBud 🙋‍♀️,  

Great work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Good PR title
✔️ No linter errors

# Status: Approved ✔️ 

![done](https://user-images.githubusercontent.com/38088818/185961577-b32d9ed4-414a-41c8-abb7-c8dfdff83af3.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 15:46 UTC, merged